name: CI

on:
  push:
    branches: [ master, github-action, test]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    name: Test on .NET ${{ matrix.dotnet-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        dotnet-version: [ '2.1.x', '2.2.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --collect="XPlat Code Coverage" --verbosity normal

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          flags: ${{ runner.os }}

      - name: Notification
        if: always()
        id: slack
        uses: wingify/slack-github-action@v1.15.1-wingify
        with:
          channel-id: 'fs-review-team'
          slack-message: "<!here> Test on *.NET Standard-${{ matrix.dotnet-version }}* and *${{ matrix.os }}* got *${{job.status}}* ${{job.status == 'success' && ':heavy_check_mark:' || ':x:'}} \nCommit: `${{github.event.head_commit.message}}`. \nCheck the latest build: https://github.com/wingify/vwo-dotnet-sdk/actions"
          color: "${{job.status == 'success' && '#00FF00' || '#FF0000'}}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
